// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsisniizlaclidxaeylt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zaXNuaWl6bGFjbGlkeGFleWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjQ4MjAsImV4cCI6MjA3MzQ0MDgyMH0.lM5nFyzacihYF9GL54ExKBYanez3e8tFfXw_psPmQJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});